"""Builder for Cosmos ProfileConfig from dbt.yml configuration."""

import os
from typing import Any, Dict

from cosmos.config import ProfileConfig


def build_profile_config(dbt_config: Dict[str, Any]) -> ProfileConfig:
    """
    Build Cosmos ProfileConfig from dbt.yml configuration.

    Assumes profiles.yml already exists at profile_dir_path (generated by dp cli
    or other tooling). Cosmos will read the existing profiles.yml file.

    Args:
        dbt_config: Dictionary from dbt.yml containing:
            - target: Target name to use (passed to dbt --target flag)
            - target_type: Target type (e.g., snowflake, bigquery)
            - profile_dir_path: Path to directory containing profiles.yml (default: /root/.dbt)
            - profile_name: (optional) Override profile name, defaults to target_type

    Returns:
        Cosmos ProfileConfig instance

    Example dbt.yml:
        target: env_execution
        target_type: snowflake
        project_dir_path: /dbt
        profile_dir_path: /root/.dbt

    Note:
        For backward compatibility, profile_name defaults to target_type (e.g., 'snowflake')
        rather than target (e.g., 'env_execution'), matching the common profiles.yml pattern.
    """
    target = dbt_config.get("target", "local")
    profile_dir = dbt_config.get("profile_dir_path", "/root/.dbt")
    profile_name = dbt_config.get("profile_name") or dbt_config.get("target_type", target)

    profiles_yml_path = os.path.join(profile_dir, "profiles.yml")

    return ProfileConfig(
        profile_name=profile_name,
        target_name=target,
        profiles_yml_filepath=profiles_yml_path,
    )
